import type {
  Customer,
  Address,
  LoanApplication,
  Loan,
  Repayment,
  Penalty,
  TopUp,
  LoanClosure,
  Voucher,
  Journal,
  Transaction,
  CollectionSchedule,
  Partner,
  User,
  LoanProduct,
} from "./types"

// In-memory data store
export const mockData = {
  partners: [
    {
      id: 1,
      name: "Delhi Financial Services",
      code: "DFS001",
      status: "Active" as const,
      servicingPincodes: ["110001", "110002", "110003", "110004", "110005"],
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 2,
      name: "Mumbai Credit Solutions",
      code: "MCS002",
      status: "Active" as const,
      servicingPincodes: ["400001", "400002", "400003", "400004", "400005"],
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 3,
      name: "Bangalore Micro Finance",
      code: "BMF003",
      status: "Active" as const,
      servicingPincodes: ["560001", "560002", "560003", "560004", "560005"],
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
  ] as Partner[],

  users: [
    {
      id: 1,
      name: "Admin User",
      email: "admin@lms.com",
      role: "admin" as const,
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 2,
      name: "Delhi Staff",
      email: "delhi@lms.com",
      role: "staff" as const,
      partnerId: 1,
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 3,
      name: "Mumbai Staff",
      email: "mumbai@lms.com",
      role: "staff" as const,
      partnerId: 2,
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 4,
      name: "Bangalore Staff",
      email: "bangalore@lms.com",
      role: "staff" as const,
      partnerId: 3,
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
  ] as User[],

  customers: [
    {
      id: 1,
      name: "Arun Kumar",
      phone: "9999999999",
      email: "arun@example.com",
      dob: "1990-01-01",
      gender: "Male" as const,
      guardianName: "Rajesh Kumar",
      occupation: "Software Engineer",
      incomeSource: "Salary",
      monthlyIncome: 75000,
      kycStatus: "Verified" as const,
      pincode: "110001",
      partnerId: 1,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: 2,
      name: "Neha Singh",
      phone: "8888888888",
      email: "neha@example.com",
      dob: "1992-02-10",
      gender: "Female" as const,
      guardianName: "Ramesh Singh",
      occupation: "Marketing Manager",
      incomeSource: "Salary",
      monthlyIncome: 65000,
      kycStatus: "Verified" as const,
      pincode: "400001",
      partnerId: 2,
      createdAt: "2024-01-20T10:00:00Z",
    },
    {
      id: 3,
      name: "Priya Sharma",
      phone: "7777777777",
      email: "priya@example.com",
      dob: "1988-05-15",
      gender: "Female" as const,
      guardianName: "Suresh Sharma",
      occupation: "Business Owner",
      incomeSource: "Business",
      monthlyIncome: 120000,
      kycStatus: "Pending" as const,
      pincode: "560001",
      partnerId: 3,
      createdAt: "2024-02-01T10:00:00Z",
    },
    {
      id: 4,
      name: "Rahul Verma",
      phone: "6666666666",
      email: "rahul@example.com",
      dob: "1985-08-20",
      gender: "Male" as const,
      guardianName: "Amit Verma",
      occupation: "Doctor",
      incomeSource: "Salary",
      monthlyIncome: 150000,
      kycStatus: "Verified" as const,
      pincode: "110002",
      partnerId: 1,
      createdAt: "2024-02-05T10:00:00Z",
    },
    {
      id: 5,
      name: "Sita Patel",
      phone: "5555555555",
      email: "sita@example.com",
      dob: "1995-12-03",
      gender: "Female" as const,
      guardianName: "Rajesh Patel",
      occupation: "Teacher",
      incomeSource: "Salary",
      monthlyIncome: 45000,
      kycStatus: "Verified" as const,
      pincode: "400002",
      partnerId: 2,
      createdAt: "2024-02-10T10:00:00Z",
    },
  ] as Customer[],

  addresses: [
    {
      id: 1,
      customerId: 1,
      type: "permanent" as const,
      line1: "123 Main St",
      line2: "Apartment 4B",
      city: "Delhi",
      state: "Delhi",
      pincode: "110001",
      isVerified: true,
      verificationDate: "2024-01-20T10:00:00Z",
    },
    {
      id: 2,
      customerId: 1,
      type: "residence" as const,
      line1: "456 Home Rd",
      line2: "House No. 15",
      city: "Delhi",
      state: "Delhi",
      pincode: "110002",
      isVerified: true,
      verificationDate: "2024-01-20T10:00:00Z",
    },
    {
      id: 3,
      customerId: 2,
      type: "permanent" as const,
      line1: "789 Park Avenue",
      line2: "Flat 12C",
      city: "Mumbai",
      state: "Maharashtra",
      pincode: "400001",
      isVerified: true,
      verificationDate: "2024-01-25T10:00:00Z",
    },
    {
      id: 4,
      customerId: 3,
      type: "permanent" as const,
      line1: "321 Business Center",
      line2: "Office 5A",
      city: "Bangalore",
      state: "Karnataka",
      pincode: "560001",
      isVerified: false,
    },
  ] as Address[],

  loanApplications: [
    {
      id: 1,
      customerId: 1,
      amount: 50000,
      product: "Personal Loan",
      purpose: "Home Renovation",
      interestRate: 12,
      tenureMonths: 12,
      repaymentFrequency: "Monthly" as const,
      status: "Approved" as const,
      createdAt: "2024-02-01T10:00:00Z",
      updatedAt: "2024-02-05T10:00:00Z",
      coApplicantIds: [2],
      guarantorIds: [],
    },
    {
      id: 2,
      customerId: 2,
      amount: 100000,
      product: "Business Loan",
      purpose: "Business Expansion",
      interestRate: 15,
      tenureMonths: 24,
      repaymentFrequency: "Monthly" as const,
      status: "Under Review" as const,
      createdAt: "2024-02-10T10:00:00Z",
      updatedAt: "2024-02-10T10:00:00Z",
      coApplicantIds: [],
      guarantorIds: [1],
    },
  ] as LoanApplication[],

  loans: [
    {
      id: 1,
      customerId: 1,
      applicationId: 1,
      amount: 50000,
      interestRate: 12,
      tenureMonths: 12,
      emi: 4500,
      disbursementDate: "2024-02-10T10:00:00Z",
      gracePeriodDays: 0,
      repaymentFrequency: "Monthly" as const,
      amortizationType: "EMI" as const,
      status: "Active" as const,
      coApplicantIds: [2],
      guarantorIds: [],
      createdAt: "2024-02-10T10:00:00Z",
      updatedAt: "2024-02-10T10:00:00Z",
    },
  ] as Loan[],

  repayments: [
    {
      id: 1,
      loanId: 1,
      installmentNumber: 1,
      dueDate: "2024-03-10",
      paidDate: "2024-03-10",
      paidAmount: 4500,
      expectedAmount: 4500,
      principalAmount: 4000,
      interestAmount: 500,
      paymentMode: "UPI" as const,
      isAdvancePayment: false,
      status: "Paid" as const,
      overdueDays: 0,
    },
    {
      id: 2,
      loanId: 1,
      installmentNumber: 2,
      dueDate: "2024-04-10",
      paidDate: "2024-04-12",
      paidAmount: 4500,
      expectedAmount: 4500,
      principalAmount: 4050,
      interestAmount: 450,
      paymentMode: "Cash" as const,
      isAdvancePayment: false,
      status: "Paid" as const,
      overdueDays: 2,
    },
    {
      id: 3,
      loanId: 1,
      installmentNumber: 3,
      dueDate: "2024-05-10",
      paidDate: null,
      paidAmount: 0,
      expectedAmount: 4500,
      principalAmount: 4100,
      interestAmount: 400,
      paymentMode: "Cash" as const,
      isAdvancePayment: false,
      status: "Overdue" as const,
      overdueDays: 15,
      collectionAgent: "Agent 1",
    },
  ] as Repayment[],

  collectionSchedules: [
    {
      id: 1,
      loanId: 1,
      customerId: 1,
      dueDate: "2024-06-10",
      emiAmount: 4500,
      status: "Upcoming" as const,
      overdueDays: 0,
      priority: "Low" as const,
      nextReminderDate: "2024-06-05",
    },
    {
      id: 2,
      loanId: 1,
      customerId: 1,
      dueDate: "2024-07-10",
      emiAmount: 4500,
      status: "Upcoming" as const,
      overdueDays: 0,
      priority: "Low" as const,
      nextReminderDate: "2024-07-05",
    },
  ] as CollectionSchedule[],

  penalties: [
    {
      id: 1,
      loanId: 1,
      repaymentId: 3,
      date: "2024-05-25",
      amount: 225,
      reason: "Late payment penalty",
      penaltyType: "LatePayment" as const,
      calculationMethod: "PerDay" as const,
    },
  ] as Penalty[],

  topUps: [] as TopUp[],

  loanClosures: [] as LoanClosure[],

  vouchers: [
    {
      id: 1,
      type: "Receipt" as const,
      amount: 4500,
      note: "EMI Payment - Installment 1",
      customerId: 1,
      loanId: 1,
      date: "2024-03-10T10:00:00Z",
    },
    {
      id: 2,
      type: "Receipt" as const,
      amount: 4500,
      note: "EMI Payment - Installment 2",
      customerId: 1,
      loanId: 1,
      date: "2024-04-12T10:00:00Z",
    },
  ] as Voucher[],

  journals: [
    {
      id: 1,
      entry: "Interest Accrued - Installment 1",
      loanId: 1,
      amount: 500,
      type: "Credit" as const,
      date: "2024-03-10T10:00:00Z",
    },
    {
      id: 2,
      entry: "Principal Reduction - Installment 1",
      loanId: 1,
      amount: 4000,
      type: "Debit" as const,
      date: "2024-03-10T10:00:00Z",
    },
  ] as Journal[],

  transactions: [
    {
      id: 1,
      customerId: 1,
      loanId: 1,
      description: "EMI Payment - Principal",
      amount: 4000,
      type: "Credit" as const,
      date: "2024-03-10T10:00:00Z",
    },
    {
      id: 2,
      customerId: 1,
      loanId: 1,
      description: "Interest Accrued",
      amount: 500,
      type: "Credit" as const,
      date: "2024-03-10T10:00:00Z",
    },
  ] as Transaction[],

  loanProducts: [
    {
      id: 1,
      name: "Personal Loan",
      code: "PL001",
      description: "Unsecured personal loan for various purposes",
      category: "Personal" as const,
      minAmount: 10000,
      maxAmount: 500000,
      minTenureMonths: 12,
      maxTenureMonths: 60,
      interestRate: 12.5,
      processingFee: 1000,
      prepaymentPenalty: 2,
      latePaymentPenalty: 2,
      eligibilityCriteria: {
        minAge: 21,
        maxAge: 65,
        minIncome: 25000,
        requiredDocuments: ["PAN Card", "Aadhaar Card", "Bank Statements", "Salary Slips"],
        creditScoreRequired: true,
      },
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 2,
      name: "Business Loan",
      code: "BL001",
      description: "Loan for business expansion and working capital",
      category: "Business" as const,
      minAmount: 50000,
      maxAmount: 2000000,
      minTenureMonths: 24,
      maxTenureMonths: 84,
      interestRate: 15.0,
      processingFee: 2000,
      prepaymentPenalty: 3,
      latePaymentPenalty: 3,
      eligibilityCriteria: {
        minAge: 25,
        maxAge: 60,
        minIncome: 50000,
        requiredDocuments: ["PAN Card", "Aadhaar Card", "Business Registration", "Bank Statements", "IT Returns"],
        creditScoreRequired: true,
      },
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 3,
      name: "Home Loan",
      code: "HL001",
      description: "Secured loan for home purchase and construction",
      category: "Home" as const,
      minAmount: 500000,
      maxAmount: 10000000,
      minTenureMonths: 60,
      maxTenureMonths: 240,
      interestRate: 8.5,
      processingFee: 5000,
      prepaymentPenalty: 2,
      latePaymentPenalty: 2,
      eligibilityCriteria: {
        minAge: 21,
        maxAge: 65,
        minIncome: 40000,
        requiredDocuments: ["PAN Card", "Aadhaar Card", "Bank Statements", "Salary Slips", "Property Documents"],
        creditScoreRequired: true,
      },
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 4,
      name: "Car Loan",
      code: "CL001",
      description: "Vehicle financing for new and used cars",
      category: "Vehicle" as const,
      minAmount: 200000,
      maxAmount: 2000000,
      minTenureMonths: 12,
      maxTenureMonths: 84,
      interestRate: 10.5,
      processingFee: 1500,
      prepaymentPenalty: 2,
      latePaymentPenalty: 2,
      eligibilityCriteria: {
        minAge: 21,
        maxAge: 65,
        minIncome: 30000,
        requiredDocuments: ["PAN Card", "Aadhaar Card", "Bank Statements", "Salary Slips", "Driving License"],
        creditScoreRequired: false,
      },
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
    {
      id: 5,
      name: "Education Loan",
      code: "EL001",
      description: "Loan for higher education and skill development",
      category: "Education" as const,
      minAmount: 50000,
      maxAmount: 1000000,
      minTenureMonths: 24,
      maxTenureMonths: 120,
      interestRate: 9.5,
      processingFee: 1000,
      prepaymentPenalty: 1,
      latePaymentPenalty: 2,
      eligibilityCriteria: {
        minAge: 18,
        maxAge: 35,
        minIncome: 0, // Student loans may not require income
        requiredDocuments: ["PAN Card", "Aadhaar Card", "Admission Letter", "Fee Structure", "Co-applicant Documents"],
        creditScoreRequired: false,
      },
      status: "Active" as const,
      createdAt: "2024-01-01T10:00:00Z",
      updatedAt: "2024-01-01T10:00:00Z",
    },
  ] as LoanProduct[],
}

export function getNextId<T extends { id: number }>(array: T[]): number {
  return Math.max(...array.map((item) => item.id), 0) + 1
}
